### ISSUE TITLE
tackx flow T1680 with Tacx Upgrade Virtual reality kit with a T1932, some help appreciated.

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#14]
@totalreverse I get below question; would this configuration work like the Tacx i-Vortex?

https://github.com/WouterJD/FortiusANT/issues/14#issuecomment-694770772

"I realised I still had an old Tacx Flow stored in my attic. I saw the software project you developed and I'm triggered to give it a try as I would like to use Zwift or Rouvy during the winter :-).

I would like to know if my tackx flow is compatible with the software. I have a tackx flow T1680 but I realised it doesn't have the possibility to connect it to a laptop through USB. I am able to buy a second hand Tacx Upgrade Virtual reality kit with a T1932 interface."

**Comment by totalreverse** [comment]
It should work. The T1932 can drive a T1901. I would give it a try.

**Comment by WouterJD** [comment]
Thanks

**Comment by StFalagar** [comment]
Hi @WouterJD 

Thanks for the email...  my name is Sarel and I am from South Africa.  I have been using a T1901 but it still has the standard head unit without USB so therefore I was looking at @totalreverse solution to try and replace the headunit with a Raspberry Pi.
I have since bought a Fortius with T1932 head unit and should get it early next week... I have also already downloaded FortiusAnt and the BTE Config so just waiting for the new trainer and BTE Dongles and I should be up and running (fingers crossed).  I'll keep following the posts regarding replacing the Head Unit with a raspberry pi or cable since I would like to get the T1901 working on Zwift/Trainerroad/Rouvy Etc.

Thanks for all your efforts etc.  Really appreciate it... else it would have been a while before I could get onto these new platforms...

**Comment by WouterJD** [comment]
Hi @StFalagar good luck with your headunit development!
Keep me posted on the progress with your Fortius; I have two myself - one ANT- and one BLE-communicating.
