### ISSUE TITLE
Fortius Grade to Resistance formula

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#2]
ANT sends a grade through page51 and this grade is to be converted to trainer resistance.

I find following formula's:
> documentation:      LOAD ~= (slope (in %) - 0.4) * 650
> ttyT1941.py:            SlopeScale =  2 * 5 * 130    = 1300
>                                 commented  = 13 * 5 * 10 * 5 = 3250

Connecting to ZWIFT I receive lower grades than displayed by Zwift (ANT Page 51).
To get the readings in line, I use a *2.5 factor on the grade.
This factor is close to the difference of 1300 and 650.

Any explanation for this phenomenon?
What is the background of the 650 / 1300 / 3250?

**Comment by totalreverse** [comment]
Short answer: Probably all formulas are wrong.

First, the weight, one can set in command byte #9 to switch the trainer to "slope mode" **probably** does not change the resistance of the trainer. The weight-value may change the effect of the "virtual fly wheel", if you stop pedalling. 
Second, the firmware of the T1932 **maybe** behaves different than the firmware for the T1942. 

The whole thing **really** needs further investigations!).

----

How do you connect your trainer to ZWIFT? Are you sure, that the software use an appropriate  model to drive the trainer?

----

I now think, that the best way is to calculate a force for a given weight (rider&bike), slope and speed. Then just set the trainer resistance to this value. 

ANT+ describes a simple physical model:

* Total resistance [N] = Gravitational Resistance + Rolling Resistance + Wind Resistance
* Gravitational Resistance [N] = (Equipment Mass + User Mass) x Grade(%)/100 x 9.81

With the assumption of a total weight of about 80 kg and without rolling and wind resistance together with the simple assumption `Load = Force [N] * 137`  (the result of a fitting in ergo mode) one get:

`Load = 137 * 80 * 9.81 * slope_in_percent / 100`

`SlopeScale = 137 * 80 * 9.81 / 100 = 1075` 

which is somewhere between the 650 and 1300.

**Comment by WouterJD** [comment]
"probably does not change the resistance of the trainer"
Well, it DOES change the behaviour of the trainer. Weight=10 causes resistance to be constant; lower cadence requires more force to achieve constant power. Why 10? Perhaps because it's the default weight for a bike. Who knows.
This piece of your description made Antifier work!

Also when TargetPower=0 Wieght=10 the Fortius has no resistance (Ergo mode).
At another Weigth, the Fortius works in 0% grade mode and has flat rode resistance.
(I will recheck whether this is true)

**Comment by WouterJD** [comment]
How do you connect your trainer to ZWIFT?

I receive ANT commands through a dongle (Zwift is running on another laptop) and send trainer commands through USB interface. Conceptually as Antifier works. (As soon as I am happy with the code quality, I will publish on github)

**Comment by WouterJD** [comment]
SlopeScale = somewhere between the 650 and 1300
[I would still be curious what your source of information is; did you reverse engineer this all?]

When I ride the Fortius/Zwift and set the resistance (using formula), at a given gear, the Fortius gives 40km/hr where Zwift displays 20km/hr.
Since there is no discussion on power or cadence (Zwift displays expected values) the trick must be that the resistance is too low for the grade.

I will do an experiment: at a given grade, set resistance so that the speed calculated by Zwift matches the wheelspeed of the bike on the Fortius. To be achieved by varying the SlopeScale.

**Comment by totalreverse** [comment]
Yes, the weight changes the behavior of the trainer but it does not 'correct' a targetLoad for a given 'slope'. 
If the trainer would simulate a real mass riding up a hill, then changing the weight should have an effect on the force for a given slope. But there is no change of the trainer force, if you change the mass while riding with constant speed for a given slope (= constant load). 
The trainer just do not know something about 'slopes' and there is no 'ergo mode' or 'slope mode'. There is only a 'calibration mode' (mode=0x3, targetLoad controls the speed of the trainer) and a 'force mode' (mode=0x2, targetLoad controls the force of the trainer). 

But let me explain: 

I have done some tests today (without a power meter) and now I am fairly sure, that the 'weight' value controls **only** some kind of "virtual fly wheel". 

Values under 0x0a results in some strange effects but at least for values above 0x0a, changing the 'weight' has an effect on the 'responsiveness' of the trainer, if you change the speed (acceleration != 0) 
For higher weights, the trainer is less responsive, if you increase the speed (acceleration > 0) and on the other side the trainer runs a little longer if you stop pedaling (acceleration < 0) . 

The trainer seems to simulate a fly wheel, which needs some extra power to 'virtual accelerate' if you accelerate the trainer and gives back some (virtual kinetic) energy if you reduce the speed. 
Internally the trainer adds some force to the 'targetLoad', if you increase the speed and reduces the force if you decrease the speed. 

After this test I probably should change the documentation of the answer frame (byte offsets for T1942 answer frames - subtract 24 bytes for raw T1941 answers): 

Byte 40/41 is the raw (bounced) "targetLoad" from the command. 
Byte 38/39 is the real load (targetLoad +/- virtualFlyWheelLoad) 
Byte 36/37 is the some kind of avg. (real) load 
Byte 34/35 is a function of the speed-difference (maybe just a simple delta between two 'rawSpeed' values for a given time ==> +/- acceleration)

Byte 34/35 probably is (together with the 'weight' value of the command) the input value to compute the VirtualFlyWheelLoad: 
* `realLoad = targetLoad + flyWheelLoad(acceleration, weight)` 

As long as you do not change the speed (acceleration = 0) , the values for  targetLoad, realLoad and (after a while) the avgRealLoad shows the same values, because the effect of the virtual fly wheel is "0". The 'weight' value has NO effect now. 

Result: 
* **In 'force mode=0x2', trainer 'load' is always linear to a force** (maybe with a little offset for calibration).

As I wrote above, the unit of "1 load" is equivalent to about 137 N. Negative values are possible. In this case the trainer further accelerates if you stop pedalling. 

As long as you do not know the effect of the virtual fly wheel, it is probably a good idea to reduce the 'weight' to a small value and just simulate all of physics by your own. Probably weight=0x0a is a good choice.

**Comment by WouterJD** [comment]
mode = 2 = ForceMode seems a logical name (instead of Ergo/Slope mode).
weight = flywheel wight seems a good idea.

Test executed:
----------------
I have tested mode = 2 (resistance) and weight = 0, 10, ... 200

I confirm the behaviour as suggested; it is as if this Weight is a flywheel weight; 10 is reasonable smooth, where 200 is difficult to speed-up. As soon as rotating, I feel no clear difference. But when slowing down, the trainer remains rotating very long (heavy flywheel).

Weight=<10 causes different behaviour, as if a default higher weight is assumed (as you state above).

I started off with antifier, which uses a standard value 0f 0x52 (82 kg) (trainer.py send()). As soon as changed into 0x0a (as suggested earlier) the trainer worked a lot better. That's why the suggestion "weight=0x0a together with mode=2 switchs to ERGO mode." seemed plausible.

**Comment by WouterJD** [comment]
It appears that I can confirm that the calibration field indicates the force that is required without the brake being active (resistance of the system, roller and tyre).

Test executed:
----------------
Target power = 100W, cadence = 70, calibration = 0...16 x 130 (default = 8 * 130).
If Calibrate (bytes 10,11) > Power (bytes 4,5) the engine starts pushing instead of braking.
If Calibrate = 0 more pedal-force is required than higher values.

It appears that the actual force applied = Target - Calibrate.

Additional tests:
------------------
Some additional tests and behaviours, confirming the previous:
When mode=2, Target=0 AND Calibrate = 0, pedalling requires no force at all.
When mode=2, Target=0 AND Calibrate = 2000, you're riding an e-bike.

**Comment by WouterJD** [comment]
Thanks for support, this issue can be closed as well.
