### ISSUE TITLE
Thanks to your definitions, FortiusANT now exists.

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#3]
TotalReverse, please check https://github.com/WouterJD/FortiusANT/; I would appreciate any feedback!

**Comment by totalreverse** [comment]
Very nice! Good work (And thanks for pushing me to do some further investigations).
You're idea of - what I would call - a 'virtual gear' is very interesting.

My own project (the ezTraCon firmware) still isn't good enough to push it upstream. 

----

I had a a very rough look into your code:

1. You can use python to load the original T1942 firmware (i.e. see my fxload.py project. So you do not need an external OS dependent program )

2. You're using the old power model with the Power2LoadMagic?

I think my last  formula was the best fit:

`  power = a + b1_1040 * rawSpeed + c1 * commandLoad * rawSpeed`

with  
````
a ~= -35.4, 
b1_1040 ~= 0.006004984, 
c1 ~= .0000070529
````

Combining b1_1040 and c1 to offsetLoad and with new name rawSpeed = v_raw, c1= scaleLoad, a = offsetPower one get

`  power = offsetPower + scaleLoad * (offsetLoad +  load) * v_raw`

with  
````
offsetPower ~= -35.4, 
offsetLoad ~= 851,4
scaleLoad ~= .0000070529`
1 / scaleLoad = 141785 (comparable to the 'old' Power2LoadMagic)
````

The offsetLoad is the value for my system with calibration of 1040=0x410. Now it is better to see, that the offsetLoad is just another calibration value. And
`  totalOffset = offsetLoad + calibration` 

The old formula 

`  power = const * raw-load * raw-speed`

assumes 
````
  offsetPower=0 
  offsetLoad=0 
  scaleLoad = const = 1/power2loadMagic ~= 0.00000775 
````

3. Your simulation model uses the assumption `load = 137 * force` ?

This assumes `offsetPower = 0` (and `velocityScale_kph=289.75`) because 

`forceScale = 141785 / 289.75 / 3.6 = `**136**  

`3.6` is to get mps instead of kph - and I do not know why I calculated 137 the last time.

`slopeOffset = -0.4`  is probably comparable to `offsetLoad = 544`. 

I used the 137 just to show in a rough calculation, that the old "slope model' was wrong. 

I think the best thing is to use 

***`  power = offsetPower + scaleLoad * (offsetLoad +  load) * v_raw`***

(maybe with little tuned values for offsetPower, scaleLoad and offsetLoad) and then use standard physics 

`P = F_simulation * v`
`v = v_raw / velocityScale_kph / 3.6`

`Load = (F_simulation * v - offsetPower) / scaleLoad / v_raw - offsetLoad`

For F_simulation have a look at http://www.kreuzotter.de/english/espeed.htm. But I think your model is good, too.
